[profile.release]
panic = 'unwind'

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
    'node',
    'modules/*',
    'runtime',
    'primitives',
    'pallets/*',
]
exclude = ['rpc']
