[package]
name = "orml-oracle-rpc-runtime-api"
version = "0.4.1-dev"
authors = ["Laminar Developers <hello@laminar.one>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-api = { default-features = false, version = "3.0.0" }
sp-std = { default-features = false, version = "3.0.0" }

funty = { version = "=1.1.0", default-features = false } # https://github.com/bitvecto-rs/bitvec/issues/105

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-api/std",
	"sp-std/std"
]
